#ifndef __MEMORY_LAYOUT_H_
#define __MEMORY_LAYOUT_H_


#define PAGE_NUMS 255
#define PAGE_SIZE 2048
#define BASS_ADDRESS 0x08000000

#define BKP_1_PAGE (PAGE_NUMS-100)
#define BKP_1_START_ADDR (BASS_ADDRESS+(BKP_1_PAGE*PAGE_SIZE))

#define BKP_2_PAGE (PAGE_NUMS-99)
#define BKP_2_START_ADDR (BASS_ADDRESS+(BKP_2_PAGE*PAGE_SIZE))

#define BKP_3_PAGE (PAGE_NUMS-98)
#define BKP_3_START_ADDR (BASS_ADDRESS+(BKP_3_PAGE*PAGE_SIZE))

#define BKP_4_PAGE (PAGE_NUMS-97)
#define BKP_4_START_ADDR (BASS_ADDRESS+(BKP_4_PAGE*PAGE_SIZE))

#define BKP_5_PAGE (PAGE_NUMS-96)
#define BKP_5_START_ADDR (BASS_ADDRESS+(BKP_5_PAGE*PAGE_SIZE))

#define BKP_6_PAGE (PAGE_NUMS-95)
#define BKP_6_START_ADDR (BASS_ADDRESS+(BKP_6_PAGE*PAGE_SIZE))

#define BKP_7_PAGE (PAGE_NUMS-94)
#define BKP_7_START_ADDR (BASS_ADDRESS+(BKP_7_PAGE*PAGE_SIZE))

#define BKP_8_PAGE (PAGE_NUMS-93)
#define BKP_8_START_ADDR (BASS_ADDRESS+(BKP_8_PAGE*PAGE_SIZE))

#define BKP_9_PAGE (PAGE_NUMS-92)
#define BKP_9_START_ADDR (BASS_ADDRESS+(BKP_9_PAGE*PAGE_SIZE))

#endif